/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  StSkycons as StSkycons
} from './components/st-skycons/st-skycons';

declare global {
  interface HTMLStSkyconsElement extends StSkycons, HTMLStencilElement {
  }
  var HTMLStSkyconsElement: {
    prototype: HTMLStSkyconsElement;
    new (): HTMLStSkyconsElement;
  };
  interface HTMLElementTagNameMap {
    "st-skycons": HTMLStSkyconsElement;
  }
  interface ElementTagNameMap {
    "st-skycons": HTMLStSkyconsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "st-skycons": JSXElements.StSkyconsAttributes;
    }
  }
  namespace JSXElements {
    export interface StSkyconsAttributes extends HTMLAttributes {
      autoplay?: boolean;
      color?: string;
      height?: string;
      icon?: string;
      width?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
